export default [
    { id: 1, name: "John Doe", grade: 90 },
    { id: 2, name: "Jane Doe", grade: 95 },
    { id: 3, name: "Jim Doe", grade: 85 },
    { id: 4, name: "Jill Doe", grade: 80 },
    { id: 5, name: "Jack Doe", grade: 75 },
    { id: 6, name: "Jenny Doe", grade: 70 },
    { id: 7, name: "Jerry Doe", grade: 65 },
    { id: 8, name: "Judy Doe", grade: 60 },
    { id: 9, name: "Jesse Doe", grade: 55 },
    { id: 10, name: "Jasmine Doe", grade: 50 },
    { id: 11, name: "Jasper Doe", grade: 45 },
    { id: 12, name: "Jared Doe", grade: 40 },
    { id: 13, name: "Joc    Doe", grade: 35 },
];